# Generated by Django 5.1.1 on 2024-10-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_livro_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
