// DEVER DE CASA:

// CRIAR UMA PÁGINA DE LOGIN COM DOIS INPUTS (EMAIL E SENHA) E UM BOTÃO "LOGIN"
// CRIAR UM ARQUIVO JS , DEFINIR QUAIS É A SENHA E O EMAIL CORRETO.
// QUANDO O BOTÃO LOGIN FOR CLICADO A SENHA E O EMAIL DEVEM SER CHECADOS
// CASO INCORRETOS UMA MESNSAGEM DE ERRO DEVE SER EXIBIDA ABAIXO DO INPUT
// CASO BEM SUCEDIDO UMA MENSAGEM DE SUCESSO DEVE SER EXIBIDA ABAIXO DO INPUT.
